Repository frc-862/nautilus, pull requests merged in 2025-01, with the labels that each got.

#21 [#12] - implement tx based auto align for photonvision
  src/main/java/frc/robot/commands/TestAutoAlign.java
Labels: proto

#20 6 photonlib
  simgui-ds.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/PhotonVision.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: Sys-Drivetrain, vision

#24 15 create base elevator subsystem
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: proto, Sys-Elevator

#25 16 create base wrist subsystem
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Elevator.java
  src/main/java/frc/robot/subsystems/Wrist.java
Labels: proto

#22 [#11] - implemented coral positions in constants
  src/main/deploy/pathplanner/paths/Example Path.path
  src/main/java/frc/robot/Constants.java
Labels: proto

#31 14 create lift state system
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Elevator.java
  src/main/java/frc/robot/subsystems/FishingRod.java
  src/main/java/frc/robot/subsystems/Wrist.java
Labels: Sys-Elevator, Sys-Wrist, Sys-Fishing Rod

#34 [#33] swapped it!
  src/main/java/frc/robot/subsystems/FishingRod.java
Labels: cleanup, Sys-Fishing Rod

#23 [#9] - auton standin
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/StandinCommands.java
Labels: proto, auton

#36 30 add documentation the wrist subsystem
  src/main/java/frc/robot/subsystems/Wrist.java
Labels: documentation

#41 40 create approximate coral placement map
  src/main/java/frc/robot/Constants.java
Labels: Sys-Elevator, Sys-Wrist

#42 [#9] - implemented standin commands for states enum
  src/main/java/frc/robot/commands/StandinCommands.java
Labels: Sys-Fishing Rod

#51 [#50] add button binding
  src/main/java/frc/robot/RobotContainer.java
Labels: Sys-Drivetrain

#56 49 implement sysid for swerve
  .SysId/sysid.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: Sys-Drivetrain

#57 [#52] Fixed field centric
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug, Sys-Drivetrain

#45 [#39] create pose based autoalign command
  simgui-ds.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/PoseBasedAutoAlign.java
Labels: Sys-Drivetrain

#88 78 prepare elevator for unit tests
  src/main/java/frc/robot/RobotContainer.java
  src/test/java/frc/robot/subsystems/ElevatorTest.java
  src/test/java/frc/robot/subsystems/WristTest.java
Labels: unit-tests

#103 94 fix build action names
  .github/dependabot.yml
  .github/workflows/gradle.yml
Labels: meta/thunder

#91 [#90] Nautilus Offsets
  src/main/java/frc/robot/Constants.java
  vendordeps/Phoenix6-replay-frc2025-latest.json
Labels: Sys-Drivetrain, robot/nautilus

#108 [#106] Just set power and expected value to 0
  src/test/java/frc/robot/subsystems/ElevatorTest.java
Labels: unit-tests

#107 98 create collector simulation
  simgui-ds.json
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: sim

#113 111 inconsistent use of tunerconstants in code
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: cleanup

#109 [#93] Simulate Robot with Github Actions
  .github/run_sim_timeout.sh
  .github/workflows/gradle.yml
  .github/workflows/linter.yml
  .github/workflows/simulate.yml
Labels: proto, meta/thunder, sim

#121 [#120] Cleanup photonvision + fix simulation
  src/main/java/frc/robot/subsystems/PhotonVision.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: cleanup

#122 [#119] on push
  .github/workflows/gradle.yml
  .github/workflows/simulate.yml
Labels: meta/thunder

#128 [#65] added a way to create layouts for elastic
  src/main/deploy/elastic/test.json
  src/main/java/frc/robot/Robot.java
Labels: proto

#137 [#87] Created some collector unit tests
  src/test/java/frc/robot/subsystems/CollectorTest.java
Labels: unit-tests

#142 [#135] - fixed addvisionmeasurements to have standard devs setup
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: vision

#141 [#140] made the unit test files consistent and organized
  src/test/java/frc/robot/subsystems/CollectorTest.java
  src/test/java/frc/robot/subsystems/ElevatorTest.java
  src/test/java/frc/robot/subsystems/WristTest.java
Labels: documentation, cleanup, unit-tests

#144 139 create climb subsystem
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/test/java/frc/robot/subsystems/ClimberTest.java
Labels: Sys-Climb
