Repository frc-862/nautilus, pull requests merged in 2025-02, with the labels that each got.

#138 130 create algae collector
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/AlgaeCollector.java
  src/main/java/frc/robot/subsystems/CoralCollector.java
  src/test/java/frc/robot/subsystems/AlgaeCollectorTest.java
  src/test/java/frc/robot/subsystems/CoralCollectorTest.java
Labels: Sys-Algae

#134 [#131] - added pipeline switching and logging
  src/main/java/frc/robot/subsystems/PhotonVision.java
Labels: vision

#153 71 expand wrist unit tests
  src/test/java/frc/robot/subsystems/WristTest.java
Labels: unit-tests

#158 [#156] Created the set position test
  src/test/java/frc/robot/subsystems/ElevatorTest.java
Labels: unit-tests

#159 157 slow mode and robot centric same time
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug, Sys-Drivetrain

#170 [#169] - got rid of the broken button binding
  src/main/java/frc/robot/RobotContainer.java
Labels: bug

#196 [#195] - made the multipliers apply in robotcontainer
  src/main/java/frc/robot/RobotContainer.java
Labels: bug, Sys-Drivetrain

#243 239 delete standin commands
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/StandinCommands.java
Labels: cleanup
